# Site Build Settings

# jekyll-paginate configuration
# paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

url: "https://micro-ioa.org"
baseurl: ""

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Î¼-IOA"
description:	       "a website about transaction-scale environmental accounting"
author:              "Arnaud Sors"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
